### ISSUE TITLE
Changing transaction color based on state in folded view

### ISSUE THREAD

**Issue by zamlz** [ledger/vim-ledger#111]
Is it possible to config vim-ledger to color folded transactions a specific color depending on the current state ` `, `*`, `!`, etc.

**Comment by alerque** [comment]
I don't actually know the answer to this. I don't use folding either and am not very familiar with what options there are. I can hazard a guess that this might not be possible. I'd be happy to be wrong on that, and more than willing to help along anybody that wanted to setup support for this by sending in a PR.

Even other examples of plugins that changed the fold color on a case by case basis based on *anything* would be useful as a reference to somebody that did want to set this up.

**Comment by zamlz** [comment]
Yeah I'll do some more research on the matter. Maybe this will be the
reason to finally learn how to write my own vim plugins.

**Comment by alerque** [comment]
This [SO answer about a patch](https://stackoverflow.com/a/3930799/313192) suggests to me this isn't possible out of the box (or wasn't in VIM 7.x).

Poking around other plugins I can't find *anything* that does this.

I'm going to close this issue as `can't fix` because it's something not supported by VIM, but if I've either overlooked something or support gets added I'd be happy to re-open and/or accept a contribution that added support for this. It *would* be a nice user experience!
