### ISSUE TITLE
Strange colour scheme

### ISSUE THREAD

**Issue by mvhulten** [ledger/vim-ledger#116]
The colours of the syntax highlighting look suboptimal to me.  Of course, this is subjective, but it could also be unintended and hence a bug.

```
; Light-blue comment                                                           
2000-01-01 Standard color                                                      
    Assets:Light-blue           50 EUR ; EOL brown comment                     
    Expenses:Light-blue
```
1. The two comments have two different colours; this does not seem consistent.
2. The light-blue is often used for comments and thus not optimal for account names.

I like the brown for the comments, but light-blue is maybe more common for comments, so I propose to make the EOL comments light-blue, just like the full-line comments.  Furthermore, I propose to simply use the standard color (grey in my terminal) for the account strings.

I am using the as of writing most recent commit `532979346087c029badd02c9605a4efa84ac032a`.

**Comment by alerque** [comment]
This plugin does not provide a color scheme, it provides *syntax* rules. In the VIM world those are two different things. The syntax parses the content and tags it with (somewhat) standardized group names. A color scheme then defines colors for those groups.

If you don't like the colors you are seeing you should find and set a `:colorscheme` to your taste. Whether comments are blue or brown or grey or pink is up to to the color scheme.

Just a note on comments however, there are two different groups being used because the comments are *functionally* different. One set (light blue in your scheme) is just comments, the ones you are seeing as brown are transaction comments and are actually **parsed and used** for things like transaction tags, hence putting them in two different syntax groups is appropriate. You are welcome to color both the same, but the two groupings give people the option to draw them differently.

Meanwhile the account names hat you are seeing in light blue are also a different group from the top level comments, so your color scheme is doing you a disservice by showing them in the same color.

![image](https://user-images.githubusercontent.com/173595/110111012-b17ec480-7dc0-11eb-9422-c421cdc24e7e.png)

**Comment by mvhulten** [comment]
Thank you for the quick response and good explanation.

The colorscheme `molokai` is beautiful.  I found the scheme `delek` also works very well but uses softer colours and is already part of my default Vim installation.
