### ISSUE TITLE
Trailing CR when using omni completion on Windows

### ISSUE THREAD

**Issue by syringus** [ledger/vim-ledger#151]
Hello,

I face an issue with trailing CR characters when using omni completion for account names in neovim on Windows. 
After pressing CTRL+x, o, the account names suggestions are correct, but there is a trailing CR character at the end:
![image](https://github.com/ledger/vim-ledger/assets/59570728/16dc84b4-1509-4348-bcd4-3bb136e0e385)

This behavior is caused by Windows using CRLF as new line characters and `systemlist()` function splitting lines on LF character:
https://github.com/ledger/vim-ledger/blob/281346a221434574dd7f8767a352b2bf0b218b74/ftplugin/ledger.vim#L399-L404

My quick solution is to remove CR characters from the strings in accounts list:
https://github.com/ledger/vim-ledger/blob/4fc136660e404c5acbedcc6b092ba5b2619abed4/ftplugin/ledger.vim#L402-L406

I have no experience in vimscript, so the solution is far from optimal.

Best regards,
Martin.

**Comment by alerque** [comment]
Thanks for the report. I'm not on Windows myself and so won't be able to test this much. Your solution looks a bit like a hack, but I can't think of anything better necessarily without knowing if there is some built in function to handle this. Like perhaps `systemlist()` isn't what we want, or perhaps it has arguments for handling this.

In any case, the only thig I would do for now is gate this in an `if` block behind as OS test so that it doesn't have to run on all systems. If you'd like to work that up as a PR I'd say we can get started with that until such a time as somebody has a better solution to suggest.
