### ISSUE TITLE
Autocompletion is broken since PR#78

### ISSUE THREAD

**Issue by entropitor** [ledger/vim-ledger#87]
Ever since https://github.com/ledger/vim-ledger/pull/78 autocompletion is broken for me

**Comment by alerque** [comment]
Sorry to hear something caused trouble for you. Can you be  specific about the behavior you see vs. what is expected? And also include the relevant legder related configuration from your rc? As it works for me in several configurations I tried we need to determine what is different between my testing and your usage to find the problem.

**Comment by abobov** [comment]
I have same issue here. Accounts completion works, but payee does not. No plugin or ledger configuration, all by defaults.

**Comment by yikkai95** [comment]
I am using `hledger`, and adding the following lines to `.vimrc` fixed my problem:
```vim
let g:ledger_accounts_cmd = 'hledger accounts'
let g:ledger_descriptions_cmd = 'hledger descriptions'
```
**Note**
- In order to use `hledger descriptions`, you might need to make sure `hledger` is having version 1.15 | [1](https://hledger.org/release-notes.html)

**Comment by alerque** [comment]
@yikkai95 I'm glad that works for you (it works for me too) but there is still a bug here somewhere because it should come up with a sensible default if this is not set, and fallback to parsing itself if there is not ledger binary at all available.

**Comment by abobov** [comment]
I am running Ledger 3.1.2-20190205 and it does not have `descriptions` command.
This line fix payee autocompletion.
```viml
let g:ledger_descriptions_cmd = 'ledger payees'
```

**Comment by entropitor** [comment]
For me, it's just not autocompleting anything anymore.

I've nothing special configured in my vimrc. I do use subdirectories but I'm guessing that should not cause any problems, should it?

**Comment by sanjayankur31** [comment]
it wasn't working for me either, but adding this in my `vimrc` seems to have fixed it:

```
let g:ledger_bin = 'ledger'
```

If I remove this, autocompletion stops working again. Is this a required configuration?

**Comment by abobov** [comment]
I'm think issue is actual to ledger (not hledger) because for ledger plugin set `g:ledger_bin` variable
```viml
  if executable('ledger')
    let g:ledger_bin = 'ledger'
  else
```
If it's defined it also define new variables `g:ledger_accounts_cmd`, `g:ledger_descriptions_cmd`, and no current buffer parsing proceed. The only way to activate old buffer parsing is to unlet that variables.


In my case problem was in not existent `descriptions` command and no description completion. And if I output `b:compl_cache` variable, it has `{'#': 1, 'tags': {}, 'descriptions': ['Error: Unrecognized command ''descriptions'''], 'accounts': {'Assets': {'Bank': {}}, 'Equity': {}}}`

Whoever has the same issue can `:echo b:compl_cache` and see what content is.

**Comment by alerque** [comment]
I think you're on to something @abobov, that test should be happening in reverse order. First see if the variable is set, then check if it's executable, and unset it if not.

Secondarily the argument for `ledger` should be *payees* not *descriptions*; `heldger` has both but they mean different things.

**Comment by alerque** [comment]
Thanks for the sleuthing work @abobov, that led to the problem. Problems actually, I think different people here actually had different problems and it was confusing that the symptoms were similar but causes different. Your use case anyway should be back to working out of the box.

@sanjayankur31 I am really confused by your use case and I'm not sure it is going to be fixed by this. If anything you have an opposite problem from the most others here, and the opposite to the main thing I fixed. That being said I did cleanup the logic a little bit elsewhere too and it's possible that will help you. In any case please test and open up another issue with your current RC setup if it doesn't work. By the way you can use `g:ledger_accounts_cmd` to configure fetching completions from a file other than the one you are currently editing.

@yikkai95 I added `hledger` detection, if it exists it is prioritized over `ledger`. Also if you set it manually in `g:ledger_bin` it will use the correct arguments to go with it. Please let me know if that does or doesn't work for you as expected now.

@entropitor Your situation is kind of nebulous because you never really provided enough information to debug this. I'm pretty sure what @abobov tracked down was your problem too and this will fix it. If not please provide actual details about your situation so we can work on that.

**Comment by entropitor** [comment]
I found the issue. Because the file I work in is not valid (it exits with errors) autocomplete was broken. I had to set up a `g:ledger_main` to make it work.

**Comment by alerque** [comment]
@entropitor That's an interesting point and probably worth documenting. Autocompletion is not expected to work unless the file is a valid ledger and can be fully parsed. This is a little different than some more generic autocomplete systems that can work with whatever un-parsable garbage is in a file.

**Comment by entropitor** [comment]
@alerque The file is parsing alright but the assertions are not and ledger will not generate accounts if the assertions are invalid. You need to start from another file that includes mine to get valid assertions. And thus that's why it broke

**Comment by Flimm** [comment]
It would be useful to be given a warning if autocompletion is disabled because of invalid syntax in the file.
