### ISSUE TITLE
Sort journal by primary date

### ISSUE THREAD

**Issue by pigmonkey** [ledger/vim-ledger#9]
Right now when I want to sort my journal file by the transactions' primary dates I do so by redirecting the output of `ledger print --sort d`, as demonstrated by [ledger-tidy](https://github.com/dpiddy/ledger-scripts/blob/master/ledger-tidy).

I think it would be useful if this functionality could be added to vim-ledger directly. Ideally, I would like to be able to sort the whole journal file, but also have the option of sorting only the entries that I specify. Perhaps this could be added to `formatprg`?

EMACS [ledger-mode](http://ledger-cli.org/3.0/doc/ledger3.html#Running-ledger_002dmode) apparently has this functionality with the `C-c C-s` command.

**Comment by rcaputo** [comment]
When you say "redirecting the output" do you mean that you're doing `!ledger -f - print --sort d` to sort them within vim?

**Comment by machocam** [comment]
Hey - did this ever get looked at? Would love to do this directly in vim.

**Comment by alerque** [comment]
@machocam et all: You can easily do this from inside vim by selecting the transaction range you want to modify and shipping them off to ledger with `:'<,$>!ledger -f - print`. Of course you can setup a binding for that if you like.

I'm a little confused what this "feature" would look like beyond that.

**Comment by chrpinedo** [comment]
I think that "ledger print" removes comments and I don't know if anything else

**Comment by alerque** [comment]
@chrpinedo The _reason_ `ledger print` removes comments is because they are fundamentally not a meaningful data structure in the file. Note that transaction and posting comments _are_ preserved, just not disconnected comments. What exactly would you expect it to do with them? Since there isn't any semantic data that says whether they are relevant to the transaction before them or after them or whatever, where would you put them after a sort?

Any attempt to implement this in the vim plugin will have the same issue that upstream `ledger` and `hledger` face: that particular bit of data is inherently not normalizable. There is not recognized place for it to go when re-ordering transaction, removing duplicates, adding auto-generated bits, etc.

You can use transaction comments at will because they have a meaningful attachment point in the data after parsing, but you cannot both use a manually inserted semanticaly meaningless data structure _and_ expect tools to handle it in a meaningful way.

**Comment by chrpinedo** [comment]
@alerque I thought that every comment was removed with "ledger print", but I was wrong and transaction and posting comments are preserved as you said. So I agree with you that "ledger print" should be the solucion to sort transactions.
In fact, I am beginning to use the vim configuration proposed in this blog: https://justyn.io/blog/automatically-sort-and-align-ledger-transactions-in-vim/ . It might be useful for other.
Thanks for you comments @alerque

**Comment by chrpinedo** [comment]
@alerque just a last question: do you know how to map `:'<,$>!ledger -f - print` with a vmap/vnoremap command?  I tried several things, but I was unable.

**Comment by alerque** [comment]
@chrpindo Personally I have a normal mode binding that runs this on the current paragraph (so I don't have to select it first). You can see my setup here:

https://github.com/alerque/que-vim/blob/9ad2ac47889265ecfa609017b9d82c081294223f/.config/nvim/init.vim#L806

Out of that you might also be able to make use of setting up your prefered binding to only work on ledger file types.

For your exact question, this should work:

```vim
:vmap <silent> <Leader>f :!ledger -f - print<Cr>
```

Note since this is a vmode binding you don't need to specify the range, that was probably what was tripping you up. It gives cryptic error messages about not allowing `!` or trailing characters if you compose this the wrong way.

**Comment by chrpinedo** [comment]
Thanks @alerque ! I got to set vmap as you suggested.

I think that we use `ledger print` in two different ways.

You use `ledger print` to format one transaction, and in that case normal mode is quite useful (I added also to my init.vim file).

Apart from that, I want to be able to sort all my transactions according to the date. In this case, I verified that the normal mode command `:nmap <silent> <Leader>f :!ledger -f - print -sort 'date'<Cr>` removes the accounts, tags and commodities information from the beginning of the ledger file. So, I prefer to use a visual mode command selecting previously the transactions to order. Perhaps I could put the accounts, tags and commodities in another file, I don't know...

**Comment by alerque** [comment]
@chrpinedo Personally I put my account declarations, aliases, commodities, etc. in one file, then from that file include various ledgers with actual transactions. This way the files with transactions can be normalized via `print` from top to bottom without loosing anything, but I query those same records through the master file that makes it all behave as I want. Incidentally if you do this 'right' you don't have to settle for just the output being right, you can save it back to the transactions file ... essentially normalize your transactions using aliases from the master file such that account aliases get expanded, etc.

**Comment by alerque** [comment]
Given that in the 5 years this commit has been open nobody has actually proposed a way this would actually work given ledger's file format without mutilating people's data, I'm going to close it as *wontfix*. Note as discussed in the last few comments above the essence of this can easily be setup already if you don't use all of ledger's comment types, but since it requires special care by the end user not to create data that will be lost, I don't think it's a good idea to try to add a binding as default behavior. If you know what you want to have happen you can make it happen already.

I'm happy to reevaluate if anybody can suggest what this would actually look like in practice.
